name: checkout-code
on: [push]
jobs:
  checkout-run-tests:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 13
        uses: actions/setup-java@v3
        with:
          java-version: '13'
          distribution: 'adopt'
          cache: 'maven'
      - name: Test and Build
        run: mvn --batch-mode clean verify